/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ErrorT extends SpeakeasyBase {
    /**
     * the code associated with the error returned
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code: number;

    /**
     * detailed message about the error returned
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message: string;
}
