/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PetType } from "./pettype";
import { Expose } from "class-transformer";

/**
 * A single Pet object
 */
export class Pet extends SpeakeasyBase {
    /**
     * a unique identifier for a Pet
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    /**
     * the name lovingly given to the pet
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * the type of pets allowed
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: PetType;
}
